### PR TITLE
Spago pass args

### PR DESCRIPTION
**Pull request by justinwoo**
https://github.com/justinwoo/spago2nix/issues/46

```
$ ./result/bin/spago2nix generate 2 -- --config b
getting packages..
failed to list packages:
[error] failed to read the config. error was:
[error] there's no "b" in your current location.

if you already have a spago project you might be in the wrong subdirectory,
otherwise you might want to run `spago init` to initialize a new project.

(spagorunerror "normally 1")
```

and such

### CODE REVIEW

**Comment by jamesdbrock** [comment]
I tried this out and it works!

It does require that you specify a number of concurrent jobs thought.

**Comment by justinwoo** [comment]
oh yeah, i misread what the original implementation was. i thought it required the param every time

**Comment by justinwoo** [comment]
```
$ ./result/bin/spago2nix generate -- --config a
getting packages..
Failed to list packages:
[error] Failed to read the config. Error was:
[error] There's no "a" in your current location.

If you already have a spago project you might be in the wrong subdirectory,
otherwise you might want to run `spago init` to initialize a new project.

(SpagoRunError "Normally 1")

$ ./result/bin/spago2nix generate 1 -- --config a
getting packages..
Failed to list packages:
[error] Failed to read the config. Error was:
[error] There's no "a" in your current location.

If you already have a spago project you might be in the wrong subdirectory,
otherwise you might want to run `spago init` to initialize a new project.

(SpagoRunError "Normally 1")
```

fixed it

**Comment by justinwoo** [comment]
I'll try to remember to update the README at some point.

**Pull request merged**
