### PR TITLE
Use niv to pin dependencies.

### PR DESCRIPTION
**Pull request by dhess**
This unifies all the various fetchFromGitHub instances scattered
across the multiple .nix files into a single, canonical source for
each dependency. It also pins the nixpkgs used to build the package,
to reduce impurities.

### CODE REVIEW

**Comment by justinwoo** [comment]
I do not use niv and do not plan to ever use niv, so I don't see any
merging of this PR in the future happening. Do you have some specific
wishes otherwise?

**Comment by dhess** [comment]
Yes. In the current tree, there are at least 3 different places where `fetchFromGitHub` is used to fetch `easy-purescript-nix`. If you want to update the version that's being fetched, you have to a) update the `rev` and `sha256` at each location, and b) be disciplined to keep them in sync.

It would also be nice to pin the `nixpkgs` used, rather than doing an impure `import <nixpkgs> {}` at the top of each Nix file, though that's mostly down to preference and not particularly a maintenance issue.

**Comment by justinwoo** [comment]
Yes, I agree easy purescript nix should be imported once in one file and
the same pinned nixpkgs should be used as default in all files

**Comment by dhess** [comment]
So it sounds like you agree with the change in principle, but object to the implementation, is that right?

**Comment by justinwoo** [comment]
Sorry, do you mean to come off as rude in this comment? I believe this is
basically what we have been discussing here.

**Comment by dhess** [comment]
I'm just trying to work with you here, Justin. I find it difficult to figure out what you want from contributors.

**Pull request closed without merging**
